# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: 3.11
  apt_packages:
    - python3-clang

python:
  install:
    - method: pip
      path: .
  system_packages: true

formats: all

sphinx:
  configuration: doc/conf.py
